- name: Install custom dependencies
  apt: name={{ asterisk_pkg_deps }}

- name: Check installable dependencies
  shell: >
    {{ asterisk_src_dir }}/contrib/scripts/install_prereq test |
    grep "aptitude install -y" |
    sed 's/aptitude install -y //g'
  register: install_prereq_test
  changed_when: install_prereq_test.stdout

- name: Print dependencies to be installed
  debug: msg={{install_prereq_test.stdout}}
  when: install_prereq_test.changed

- name: Install dependencies
  shell: export DEBIAN_FRONTEND=noninteractive && ./contrib/scripts/install_prereq install chdir={{ asterisk_src_dir }}
  when: install_prereq_test.changed

- name: Download mp3 source code
  command: ./contrib/scripts/get_mp3_source.sh chdir={{ asterisk_src_dir }} creates=addons/mp3/mpg123.h

- name: Configure asterisk
  command: ./configure {{ asterisk_configure_options }} chdir={{ asterisk_src_dir }}

- name: Create menuselect.makeopts
  command: make menuselect.makeopts chdir={{ asterisk_src_dir }}

- name: Do a bit of menuselect configuration
  command: "menuselect/menuselect --{{ item.value }} {{ item.key }} chdir={{ asterisk_src_dir }}"
  with_dict: "{{asterisk_menuselect }}"

- name: Run custom pre-make commands
  command: "{{ item }} chdir={{ iasterisk_srcdir }}"
  with_items: "{{ asterisk_pre_make_commands }}"

- name: Make
  command: make {{ asterisk_make_options }} chdir={{ asterisk_src_dir }}

- name: Uninstall previous version
  command: make uninstall chdir={{ asterisk_src_dir }}

- name: Install
  command: make install chdir={{ asterisk_src_dir }}

- name: Install logrotate
  command: make install-logrotate chdir={{ asterisk_src_dir }}
  
- name: Create group for asterisk
  group: name={{ asterisk_rungroup }} system=yes
  when: asterisk_rungroup != 'root'

- name: Create user for asterisk
  user: name={{ asterisk_runuser }} shell=/bin/false system=yes
  when: asterisk_runuser != 'root'

- name: Fix directory permissions
  file: state=directory recurse=yes owner={{ asterisk_runuser }} group={{ asterisk_rungroup }} path={{ item }}
  with_items:
  - "{{ asterisk_install_prefix }}/var/run/asterisk"
  - "{{ asterisk_install_prefix }}/var/lib/asterisk"
  - "{{ asterisk_install_prefix }}/var/spool/asterisk"
  - "{{ asterisk_install_prefix }}/var/log/asterisk"

- name: Install systemd service
  template: src=systemd/system/asterisk.service dest=/etc/systemd/system/

